In [1]:
# 0, 1, 2 respectively represent a food.
import numpy as np 
sample = np.array([[[0],[1]],
                  [[1],[1]],
                  [[1],[2]]])

In [2]:
print(sample.shape)

(3, 2, 1)


In [3]:
label = np.array([1, 2, 0])

In [4]:
from tensorflow.keras.utils import to_categorical # for one hot encoding

In [5]:
sample = to_categorical(sample)

In [6]:
print(sample)

[[[1. 0. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 0. 1.]]]


In [7]:
label = to_categorical(label)

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

In [9]:
model = Sequential()
#                         labels          (time, features)
model.add(layers.SimpleRNN(3, input_shape=(2, 3), 
                          activation='softmax' ))

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 3)                 21        
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='rmsprop', 
             loss='categorical_crossentropy',
             metrics=['acc'])

In [12]:
history = model.fit(sample, label, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 721ms/step - loss: 1.0692 - acc: 0.3333
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 1.0658 - acc: 0.3333
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 1.0635 - acc: 0.3333
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 1.0615 - acc: 0.3333
Epoch 5/500
1/1 [==============================] - 0s 2ms/step - loss: 1.0597 - acc: 0.3333
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 1.0581 - acc: 0.3333
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 1.0566 - acc: 0.3333
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 1.0552 - acc: 0.3333
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 1.0539 - acc: 0.3333
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 1.0526 - acc: 0.3333
Epoch 11/500
1/1 [==============================] - 0s 4ms/step - loss: 1.051

1/1 [==============================] - 0s 4ms/step - loss: 0.9729 - acc: 0.6667
Epoch 90/500
1/1 [==============================] - 0s 3ms/step - loss: 0.9719 - acc: 0.6667
Epoch 91/500
1/1 [==============================] - 0s 3ms/step - loss: 0.9710 - acc: 0.6667
Epoch 92/500
1/1 [==============================] - 0s 4ms/step - loss: 0.9700 - acc: 0.6667
Epoch 93/500
1/1 [==============================] - 0s 2ms/step - loss: 0.9691 - acc: 0.6667
Epoch 94/500
1/1 [==============================] - 0s 4ms/step - loss: 0.9681 - acc: 0.6667
Epoch 95/500
1/1 [==============================] - 0s 3ms/step - loss: 0.9672 - acc: 0.6667
Epoch 96/500
1/1 [==============================] - 0s 2ms/step - loss: 0.9662 - acc: 0.6667
Epoch 97/500
1/1 [==============================] - 0s 7ms/step - loss: 0.9653 - acc: 0.6667
Epoch 98/500
1/1 [==============================] - 0s 3ms/step - loss: 0.9643 - acc: 0.6667
Epoch 99/500
1/1 [==============================] - 0s 2ms/step - loss: 0.9634 - ac

1/1 [==============================] - 0s 2ms/step - loss: 0.8913 - acc: 0.6667
Epoch 177/500
1/1 [==============================] - 0s 3ms/step - loss: 0.8904 - acc: 0.6667
Epoch 178/500
1/1 [==============================] - 0s 4ms/step - loss: 0.8895 - acc: 0.6667
Epoch 179/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8886 - acc: 0.6667
Epoch 180/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8876 - acc: 0.6667
Epoch 181/500
1/1 [==============================] - 0s 3ms/step - loss: 0.8867 - acc: 0.6667
Epoch 182/500
1/1 [==============================] - 0s 5ms/step - loss: 0.8858 - acc: 0.6667
Epoch 183/500
1/1 [==============================] - 0s 998us/step - loss: 0.8849 - acc: 0.6667
Epoch 184/500
1/1 [==============================] - 0s 6ms/step - loss: 0.8839 - acc: 0.6667
Epoch 185/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8830 - acc: 0.6667
Epoch 186/500
1/1 [==============================] - 0s 2ms/step - loss:

1/1 [==============================] - 0s 2ms/step - loss: 0.8122 - acc: 0.6667
Epoch 264/500
1/1 [==============================] - 0s 4ms/step - loss: 0.8113 - acc: 0.6667
Epoch 265/500
1/1 [==============================] - 0s 4ms/step - loss: 0.8104 - acc: 0.6667
Epoch 266/500
1/1 [==============================] - 0s 3ms/step - loss: 0.8095 - acc: 0.6667
Epoch 267/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8086 - acc: 0.6667
Epoch 268/500
1/1 [==============================] - 0s 5ms/step - loss: 0.8078 - acc: 0.6667
Epoch 269/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8069 - acc: 0.6667
Epoch 270/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8060 - acc: 0.6667
Epoch 271/500
1/1 [==============================] - 0s 3ms/step - loss: 0.8051 - acc: 0.6667
Epoch 272/500
1/1 [==============================] - 0s 4ms/step - loss: 0.8042 - acc: 0.6667
Epoch 273/500
1/1 [==============================] - 0s 997us/step - loss:

1/1 [==============================] - 0s 3ms/step - loss: 0.7366 - acc: 1.0000
Epoch 351/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7358 - acc: 1.0000
Epoch 352/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7349 - acc: 1.0000
Epoch 353/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7341 - acc: 1.0000
Epoch 354/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7332 - acc: 1.0000
Epoch 355/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7324 - acc: 1.0000
Epoch 356/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7315 - acc: 1.0000
Epoch 357/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7307 - acc: 1.0000
Epoch 358/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7299 - acc: 1.0000
Epoch 359/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7290 - acc: 1.0000
Epoch 360/500
1/1 [==============================] - 0s 3ms/step - loss: 0

1/1 [==============================] - 0s 4ms/step - loss: 0.6656 - acc: 1.0000
Epoch 438/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6648 - acc: 1.0000
Epoch 439/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6640 - acc: 1.0000
Epoch 440/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6632 - acc: 1.0000
Epoch 441/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6624 - acc: 1.0000
Epoch 442/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6616 - acc: 1.0000
Epoch 443/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6608 - acc: 1.0000
Epoch 444/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6601 - acc: 1.0000
Epoch 445/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6593 - acc: 1.0000
Epoch 446/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6585 - acc: 1.0000
Epoch 447/500
1/1 [==============================] - 0s 5ms/step - loss: 0

In [17]:
predict = model.predict(sample)
np.argmax(predict[0]), np.argmax(predict[1]), np.argmax(predict[2])

(1, 2, 0)